print("please give me your first desired number:-")
n = input() 
print("are your sure for this number..?")
print("please give me your confirmation type \'yes\' and \'No\'")
confirmation = input()

if confirmation == "yes" : 
      print("please give me your second desired number:-")
      m = input()
elif confirmation == "No" :
      print("you don't type No, \n what you are not sure  of this number...? \n try again lator.")
      exit()
else :
      print("try again lator.")
      exit()
print()
print("you enter your first number:-" , n)
print()
print("you enter your second number:-" , m)
print()
print("                              <------------------{this is First method}------------------>")
print("when", n, "+", m, "\nSo, this is sum of two numbers : =", int(n) + int(m))
print()
print("when", n, "-", m, "\nSo, this is subtraction of two numbers: =", int(n) - int(m))
print()
print("when", n, "*", m, "\nSo, this is multiplication of two numbers: =", int(n) * int(m))
print()
print("when", n, "/", m, "\nSo, this is division of two numbers: =", int(n) / int(m))
print()
print("                              <------------------{this is second method}------------------>")
addition = int(n) + int(m)
print("addition of", n, "and", m, "is =", addition)
print()
subtraction = int(n) - int(m)
print("subtraction of", n, "and", m, "is =", subtraction)
print()
multiplication = int(n) * int(m)
print("multiplication of", n, "and", m, "is =", multiplication)
print()
division = int(n) / int(m)
print("division of", n, "and", m, "is =", division)
print()
percentage =int(n) % int(m)
print("percentage of", n, "and", m, "is =", percentage)
print()
